### ISSUE TITLE
tendies.ts: SlickBot is posting incorrect percentages for ROK stock

### ISSUE THREAD

**Issue by andrewd18** [UpsidePotential/SlickBot#40]
Today at 3 PM CDT, SlickBot posted this:

![rok_down_1_4](https://user-images.githubusercontent.com/761994/90824112-80dfad80-e2fc-11ea-9266-565fefbc1e35.png)

However, if you go to the website that you're pulling the data from, it shows ROK only lost 0.80%.

![rok_down_0_80](https://user-images.githubusercontent.com/761994/90824223-b1bfe280-e2fc-11ea-8453-565e2188bf28.png)

Checking out: https://www.tiingo.com/rok/prices you can see that the data for Aug 19 shows a drop of 232.00 down to 228.68, a drop of -1.4%.

Therefore, the 3 PM CDT post pulled old data.

**Comment by krische** [comment]
Already fixed in #38 . The new numbers are not available until 5:30 PM Eastern according to the [docs](https://api.tiingo.com/documentation/end-of-day). `adjclose` and `adjopen` are the numbers adjust for things like stock splits.

**Comment by andrewd18** [comment]
At 4:31 PM today, SlickBot posted this:

![rok_down_0_3](https://user-images.githubusercontent.com/761994/90828159-26961b00-e303-11ea-8b0f-8d41293676a6.png)

This is still incorrect.

**Comment by krische** [comment]
Accepting PRs

**Comment by krische** [comment]
From my quick research, it looks like percent should be calculated off the previous close price; not the open price. I'll fix it tonight.
